# Generated by Django 5.1 on 2024-08-08 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeName',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='url_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url1', models.CharField(max_length=500)),
                ('url2', models.CharField(max_length=500)),
                ('url3', models.CharField(max_length=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animename')),
            ],
        ),
        migrations.CreateModel(
            name='url_trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url1', models.CharField(max_length=500)),
                ('url2', models.CharField(max_length=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animename')),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_image', models.ImageField(upload_to='anime/images/')),
                ('hashtags', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animename')),
                ('watch_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.url_location')),
                ('trailer_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.url_trailer')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
